In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

targetImage = cv2.imread('images/target_image.jpg', cv2.IMREAD_COLOR)

In [2]:
def print_image(image):
    cv2.namedWindow("Sample Image", cv2.WINDOW_NORMAL)
    cv2.resizeWindow('Sample Image', 800, 800)
    cv2.imshow('Sample Image', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    cv2.waitKey(1)

In [3]:
print_image(targetImage)

In [4]:
print(targetImage.shape)
shapeY = targetImage.shape[0]
shapeX = targetImage.shape[1]

diff = 440
deltaP = 2

(720, 1280, 3)


In [5]:
k = np.array([[1,1,1],[1,1,1],[1,1,1]])*(1/9)
blurImage = cv2.filter2D(targetImage, -1, k)

print_image(blurImage)

In [102]:
# for y in range(shapeY-1):
#     for x in range(shapeX-1):
        

In [8]:
print(np.linalg.norm(np.array([253, 251, 227]) - np.array([242, 240, 216])))

19.05255888325765


In [34]:
outlines = []

outlineImage = np.zeros((shapeY,shapeX,3))
# outlineImage = targetImage.copy()

for y in range(0, shapeY-deltaP, deltaP):
    for x in range(0, shapeX-deltaP, deltaP):
        if(abs(np.linalg.norm(cv2.add(blurImage[y][x], -1*blurImage[y+deltaP][x]))) >= diff or 
           abs(np.linalg.norm(cv2.add(blurImage[y][x], -1*blurImage[y][x+deltaP]))) >= diff):
            outlines.append([y,x])
            outlineImage[y][x] = [255,0,0]

            print(blurImage[y][x], blurImage[y+deltaP][x], np.array(blurImage[y][x]) - np.array(blurImage[y+deltaP][x]))
            print(blurImage[y][x], blurImage[y][x+deltaP], blurImage[y][x] - blurImage[y][x+deltaP])
            

In [35]:
print_image(outlineImage)

In [33]:
print(blurImage[0][0])
print(blurImage[5][5])


print(cv2.add(blurImage[0][0], -1*blurImage[5][5]))
print(blurImage[0][0][0] - blurImage[5][5][0])

[234 232 208]
[251 249 225]
[[-17.]
 [-17.]
 [-17.]
 [  0.]]
239


/var/folders/rh/ldskxkh54dq07z51l4jp012r0000gn/T/ipykernel_92731/2113755707.py:6: RuntimeWarning: overflow encountered in scalar subtract
  print(blurImage[0][0][0] - blurImage[5][5][0])


cv2 이미지에서는 하나의 rgb값에서 255이상의 값들을 핸들링해야할 때(혹은 음수일 때?)등등 
RuntimeWarning: overflow encountered in scalar subtract
  print(blurImage[0][0][0] - blurImage[5][5][0])

과 같은 에러가 난다. 그래서 cv2.add함수를 사용하여 안전하게 더할 수 있게 한다